const speakersData = [
  {
    id: 1,
    name: "Gospel Chinyereugo",
    role: "Web Team Lead at Alat by Wema Bank",
    img: "https://res.cloudinary.com/dd9o3s5jj/image/upload/v1761995392/devfest%20ado-ekiti%202025/Gospel_acwhw2.png",
    bio: "Gospel is a mission-driven Software Engineer with over half a decade of experience building accessible web solutions.",
    topic: "Accessible by Default",
    x: "https://x.com/Codebug_",
    linkedin: "https://www.linkedin.com/in/gospel-chinyereugo/",
  },
  {
    id: 2,
    name: "Mileke Kolawole",
    role: "GDE Cloud Engineer",
    img: "https://res.cloudinary.com/dd9o3s5jj/image/upload/v1761995412/devfest%20ado-ekiti%202025/mileke-kolawole_hoszvj.jpg",
    bio: "Mileke is a cloud engineer with core specialization in serverless and distributed cloud systems.",
    topic: "Serverless for Startups",
    x: "https://twitter.com/milekekolawole",
    linkedin: "https://www.linkedin.com/in/oluwagbemileke-kolawole/",
    website: "https://wtfiscloud.hashnode.dev/",
  },
  {
    id: 3,
    name: "Israel Daniels",
    role: "Fintech Innovator",
    img: "https://res.cloudinary.com/dd9o3s5jj/image/upload/v1740831657/devfest%20ado-ekiti%202025/israel-daniels_wvjjoc.jpg",
    bio: "Israel Daniels is a fintech innovator and founder of Beyond, building payment solutions without borders.",
    topic: "Money Without Borders",
    x: "https://x.com/TheIsraelDan?s=09",
    email: "mailto:theisraeldaniels@gmail.com",
  },
  {
    id: 4,
    name: "David Praise",
    role: "Machine Learning Engineer",
    img: "https://res.cloudinary.com/dd9o3s5jj/image/upload/v1761995421/devfest%20ado-ekiti%202025/Bede_a7sm2i.jpg",
    bio: "David builds intelligent AI-powered solutions that improve user experience and product efficiency.",
    topic: "AI For Real People",
    x: "https://twitter.com/Daviddamilola",
    linkedin: "https://linkedin.com/in/daviddamilola",
  },
  {
    id: 5,
    name: "Bede Chukwudi",
    role: "Product Designer",
    img: "https://res.cloudinary.com/dd9o3s5jj/image/upload/v1762276484/David_Oluwabusayo_cldhqk.jpg",
    bio: "Bede designs world-class product experiences focused on accessibility, scalability, and human-centered innovation.",
    topic: "Design Beyond Screens",
    x: "https://twitter.com/BedeDominic",
  },
  {
    id: 6,
    name: "Tope Oladimeji",
    role: "Mobile Engineer / Firebase Advocate",
    img: "https://res.cloudinary.com/dd9o3s5jj/image/upload/v1761995374/devfest%20ado-ekiti%202025/tope-james-moses_daxbcg.jpg",
    bio: "Tope drives mobile innovation and developer empowerment through impactful community programs.",
    topic: "Mobile at Massive Scale",
    x: "https://twitter.com/TopeAkinyemi",
    linkedin: "https://linkedin.com/in/topeakinyemi",
  },
];

export default speakersData;
